### ISSUE TITLE
.NET Core 2.0 - вылет при подключении

### ISSUE THREAD

**Issue by pasha-zzz** [yar229/WebDavMailRuCloud#100]
При попытке подключения закрывается. Запускаю так:
"C:\Program Files\dotnet\dotnet.exe" "D:\Programs\WDMRC\wdmrc.dll" -p 6443
.NET Core Runtime 2.0, Win 10 x64 v1703

WebDAVCloudMailRu: WebDAV emulator for Cloud.mail.ru
  v.1.8.0.4
[2]: OS Version: Microsoft Windows NT 6.2.9200.0
[2]: CLR Version: 4.0.30319.42000
[2]: User interactive: True
[2]: Version: 1.8.0.4
[2]: Max threads count: 5
[2]: WebDAV server running at http://127.0.0.1:6443
[6]: OPTIONS:http://127.0.0.1:6443/:127.0.0.1:6443 - Processing
[6]: OPTIONS:http://127.0.0.1:6443/:127.0.0.1:6443 - Finished (4ms, HTTP 200)
[6]: PROPFIND:http://127.0.0.1:6443/:127.0.0.1:6443 - Processing
[6]: Cloud instance created for *****@mail.ru
[6]: HTTP:GET:https://auth.mail.ru/cgi-bin/auth
Assert Failure
Expression: [Recursive resource lookup bug]
Description: Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: ArgumentNull_Generic
Stack Trace:
   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.ArgumentNullException..ctor(String paramName)
   at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly assembly)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.ArgumentNullException..ctor(String paramName)
   at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly assembly)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.PlatformNotSupportedException..ctor()
   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at System.Net.Http.WinHttpHandler.EnsureSessionHandleExists(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.<>c.<SendAsync>b__101_0(Object s)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by yar229** [comment]
Что-то прямо даже не знаю.
Воспроизвести не смог.
Не очень внимательное гугление вроде как говорит, что это баг .NET Core, попробуйте удалить и установить заново его.

**Comment by pasha-zzz** [comment]
Дак он свежеустановленный, буквально за 5 минут до запуска

**Comment by pasha-zzz** [comment]
https://github.com/dotnet/core-setup#daily-builds
Отсюда взял 2.0.4 - ругается, что надо именно 2.0.0:

It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.

**Comment by yar229** [comment]
а попробуйте [1.8.0.9](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.8.0.9)

**Comment by pasha-zzz** [comment]
Полазил по папкам, скачал файлов, залил... походил по линкованным папкам - все работает.
А поддержку самых свежих рантаймов не включить? Сейчас там 2.0.4 и 2.1.0 есть.

**Comment by yar229** [comment]
Отлично :)

Можно, но пока не выложат на nuget.org - не буду.
