### ISSUE TITLE
Необработанное исключение при отмене закачки

### ISSUE THREAD

**Issue by VADemon** [yar229/WebDavMailRuCloud#120]
Кажется, [36] не должно вываливаться при отмене закачки файла в webdav клиенте.

```
[33]: Uploading to /Buku - Front to Back-PWROws51oWM.mkv failed with The request was aborted: The request was canceled.
[36]: Unexpected exception while handling request (method=PUT, url=http://127.0.0.1:801/Buku%20-%20Front%20to%20Back-PWROws51oWM.mkv, source=127.0.0.1
:801
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The request was aborted: The request was canceled. ---> System.IO.IOException: Cannot close stream until all bytes are written.
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   at System.Net.ConnectStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
   at System.Net.ConnectStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at YaR.MailRuCloud.Api.Base.Streams.UploadStreamHttpWebRequest.<<Initialize>b__2_0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at YaR.MailRuCloud.Api.Base.Streams.UploadStreamHttpWebRequest.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at YaR.MailRuCloud.Api.Streams.SplittedUploadStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at YaR.WebDavMailRu.CloudStore.Mailru.StoreBase.MailruStoreItem.<UploadFromStreamAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NWebDav.Server.Handlers.PutHandler.<HandleRequestAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NWebDav.Server.WebDavDispatcher.<DispatchRequestAsync>d__6.MoveNext()
---> (Inner Exception #0) System.Net.WebException: The request was aborted: The request was canceled. ---> System.IO.IOException: Cannot close stream
until all bytes are written.
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   at System.Net.ConnectStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
   at System.Net.ConnectStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at YaR.MailRuCloud.Api.Base.Streams.UploadStreamHttpWebRequest.<<Initialize>b__2_0>d.MoveNext()<---

```

**Comment by yar229** [comment]
Логично, но неприоритетно, когда-нибудь :)
