### ISSUE TITLE
Ошибка при авторизации

### ISSUE THREAD

**Issue by harizman** [yar229/WebDavMailRuCloud#129]
Раньше все было ок, затем ни с того, ни с сего такая ошибка при подключении 

> 
`System.ArgumentOutOfRangeException: Value to add was out of range.
Parameter name: value
   at System.DateTime.Add(Double value, Int32 scale)
   at YaR.MailRuCloud.Api.Extensions.DtoImportWeb.UnixTimeStampToDateTime(Double unixTimeStamp)
   at YaR.MailRuCloud.Api.Extensions.DtoImportWeb.ToFile(FolderInfoProps item, String nameReplacement)
[5]: Unexpected exception while handling request (method=PROPFIND, url=http://127.0.0.1:3332/
System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Value to add was out of range.
Parameter name: value
   at System.DateTime.Add(Double value, Int32 scale)
   at YaR.MailRuCloud.Api.Extensions.DtoImportWeb.UnixTimeStampToDateTime(Double unixTimeStamp)
   at YaR.MailRuCloud.Api.Extensions.DtoImportWeb.ToFile(FolderInfoProps item, String nameReplacement)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at YaR.MailRuCloud.Api.Extensions.DtoImportWeb.ToFolder(FolderInfoResult data, String home, Link link)
   at YaR.MailRuCloud.Api.Base.Repos.WebM1RequestRepo.<FolderInfo>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YaR.MailRuCloud.Api.MailRuCloud.<GetItemAsync>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at YaR.WebDavMailRu.CloudStore.Mailru.StoreBase.MailruStore.GetItemAsync(WebDavUri uri, IHttpContext httpContext)
   at NWebDav.Server.Handlers.PropFindHandler.<HandleRequestAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NWebDav.Server.WebDavDispatcher.<DispatchRequestAsync>d__6.MoveNext()
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Value to add was out of range.
Parameter name: value
   at System.DateTime.Add(Double value, Int32 scale)
   at YaR.MailRuCloud.Api.Extensions.DtoImportWeb.UnixTimeStampToDateTime(Double unixTimeStamp)
   at YaR.MailRuCloud.Api.Extensions.DtoImportWeb.ToFile(FolderInfoProps item, String nameReplacement)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at YaR.MailRuCloud.Api.Extensions.DtoImportWeb.ToFolder(FolderInfoResult data, String home, Link link)
   at YaR.MailRuCloud.Api.Base.Repos.WebM1RequestRepo.<FolderInfo>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YaR.MailRuCloud.Api.MailRuCloud.<GetItemAsync>d__9.MoveNext()<---`

**Comment by harizman** [comment]
Извините, если некорректно оформил. Новичок здесь. Прошу помочь.

**Comment by yar229** [comment]
Я так понимаю, что обновились со старой версии на последнюю и началось?
Какая версия до этого была?

**Comment by harizman** [comment]
Не обновлял. Случилось вчера, грузил файлы, удалял, копировал. Ничего не обычного. Потом раз и в cmd красные строчки пошли (которые указывал выше в тикете). Ужаснулся, рестартнулся, тоже самое. Затем перескачал архив WDMRC с GitHUB, ситуация та же. Затем уже написал вам. Подозревал, что связано с платным выходом Диск-О с 1 фев и может они там что-то в API изменили... (но это просто догадки)

ОС: Windows 10, антивирус eset nod32. Запускаю через cmd.

**Comment by yar229** [comment]
Посмотрите в веб-интерфейсе в папку, при заходе в которую начинает сыпаться красным.
Интересуют аномальные даты файлов (меньше 01.01.1900 или в будущем)

**Comment by harizman** [comment]
Даже не подключается, в диск зайти не могу.

**Comment by harizman** [comment]
Скрин cmd> ![default](https://user-images.githubusercontent.com/36002565/35635532-98dd0c1e-06bf-11e8-87dc-273a77b435bf.png)

**Comment by harizman** [comment]
@yar229 допедрил и зашел в веб-версию. Удалил несколько фото, которые последними вчера закидывал. Все завелось, спасибо :)

**Comment by yar229** [comment]
Если есть желание и время, попробуйте воспроизвести, пожалуйста
Интересует: 
* локальное время на вашей машине и временная зона
* дата/время создания и модификации файла, который вызывает такое поведение
* дата/время, которое показывается для такого файла в веб-интерфейсе

**Comment by harizman** [comment]
Да, постараюсь разобраться.

Время мск, utc+3.
Юзал так, закидывал некоторые jpg фото с android смартфона через cloud.mail клиент в Облако. Затем забирал фото на ПК. Было порядка 10 фото разных, трудно будет воспроизвести снова. 

Ещё вопросы есть. Что изменится если wdmrc exe добавлю в службы? Придется ли редачить cmd файл? И ещё, как сделать чтобы cmd окно wdmrc постоянно не весело на панели задач? Спасибо.

**Comment by harizman** [comment]
Инфа об этом файле в тлф:
clck.ru/CdgN5
И в приложении облака:
clck.ru/CdgPW

Сразу фотками что-то прикрепить не удалось, сори.

**Comment by yar229** [comment]
> Что изменится если wdmrc exe добавлю в службы?
> Придется ли редачить cmd файл?
Видимо, из него нужно будет убрать запуск wdmrc и оставить только то, что относится к подключению диска (`net use ....`)

> И ещё, как сделать чтобы cmd окно wdmrc постоянно не весело на панели задач?
Сделать службой :)
Ну или через Пуск -> Task Scheduler

**Comment by yar229** [comment]
Данных недостаточно, я так и не понял, что там было, но, по крайней мере, теперь падать по этой причине не будет
* в логе будет ошибка
* у таких файлов будет неправильная дата

[1.10.1.10](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.10.1.10)
