### ISSUE TITLE
Error deleting some files

### ISSUE THREAD

**Issue by yar229** [yar229/WebDavMailRuCloud#17]
[21]: Unable to delete '/Photo/2005 12/СПб - Москва/_orig' directory.
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Specified value has invalid Control characters.
Parameter name: value
   at System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)
   at System.Net.HttpWebRequest.SetSpecialHeaders(String HeaderName, String value)
   at System.Net.HttpWebRequest.set_Referer(String value)
   at MailRuCloudApi.MailRuCloud.<Remove>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailRuCloudApi.MailRuCloud.<Remove>d__27.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at YaR.WebDavMailRu.CloudStore.MailruStoreCollection.DeleteItemAsync(String name, IHttpContext httpContext)
---> (Inner Exception #0) System.ArgumentException: Specified value has invalid Control characters.
Parameter name: value
   at System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)
   at System.Net.HttpWebRequest.SetSpecialHeaders(String HeaderName, String value)
   at System.Net.HttpWebRequest.set_Referer(String value)
   at MailRuCloudApi.MailRuCloud.<Remove>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailRuCloudApi.MailRuCloud.<Remove>d__27.MoveNext()<---

**Comment by yar229** [comment]
fixed in #26 
https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.0.129
