### ISSUE TITLE
Mounting failed

### ISSUE THREAD

**Issue by barl0g** [yar229/WebDavMailRuCloud#179]
Сегодня перестало монтироваться:
```
$ mount cloud/
/sbin/mount.davfs: Mounting failed.
500 Internal Server Error
```

```
WebDAVCloudMailRu: WebDAV emulator for Cloud.mail.ru
  v.1.10.9.0
  yar229@yandex.ru
[1]: OS Version: Unix 4.8.15.9
[1]: CLR: .NET Core 3.0.1
[1]: User interactive: True
[1]: Version: 1.10.9.0
[1]: Using proxy: 
[1]: Max threads count: 5
[1]: Cloud protocol: WebM1Bin
[1]: Cache listings, sec: 30
[1]: List query folder depth: 1
[1]: WebDAV server running at http://127.0.0.1:8010/
[8]: OPTIONS:http://127.0.0.1:8010/:127.0.0.1:8010 - Start processing
[8]: OPTIONS:http://127.0.0.1:8010/:127.0.0.1:8010 - Finished processing (69ms, HTTP result: 200)
[8]: PROPFIND:http://127.0.0.1:8010/:127.0.0.1:8010 - Start processing
[8]: Cloud instance created for no@mail.ru
[8]: OAuth: authorizing.
[5]: HTTP:POST:https://o2.mail.ru/token (207 ms)
[8]: Unexpected exception while handling request (method=PROPFIND, url=http://127.0.0.1:8010/, source=127.0.0.1:8010                                                                                          
System.AggregateException: One or more errors occurred. (The remote server returned an error: (500) OK.)                                                                                                      
 ---> System.Net.WebException: The remote server returned an error: (500) OK.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at YaR.MailRuCloud.Api.Base.Requests.BaseRequest`2.<>c__DisplayClass8_0.<MakeRequestAsync>b__0(IAsyncResult asyncResult)                                                                                   
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)                                      
--- End of stack trace from previous location where exception was thrown ---
   at YaR.MailRuCloud.Api.Base.Requests.BaseRequest`2.MakeRequestAsync()
   at YaR.MailRuCloud.Api.Base.Auth.OAuth.Auth()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at YaR.MailRuCloud.Api.Base.Auth.OAuth.<.ctor>b__4_0(AuthTokenResult old)
   at YaR.MailRuCloud.Api.Common.Cached`1.<>c__DisplayClass8_0.<RefreshValueIfNeeded>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)                                                                                                
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at YaR.MailRuCloud.Api.Common.Cached`1.RefreshValueIfNeeded()
   at YaR.MailRuCloud.Api.Common.Cached`1..ctor(Func`2 valueFactory, Func`2 duration)
   at YaR.MailRuCloud.Api.Base.Auth.OAuth..ctor(HttpCommonSettings settings, IBasicCredentials creds, AuthCodeRequiredDelegate onAuthCodeRequired)                                                            
   at YaR.MailRuCloud.Api.Base.Repos.WebM1RequestRepo..ctor(IWebProxy proxy, IBasicCredentials creds, AuthCodeRequiredDelegate onAuthCodeRequired, Int32 listDepth)                                           
   at YaR.MailRuCloud.Api.Base.Repos.RepoFabric.Create()
   at YaR.MailRuCloud.Api.Base.Account..ctor(CloudSettings settings, Credentials credentials)
   at YaR.MailRuCloud.Api.MailRuCloud..ctor(CloudSettings settings, Credentials credentials)
   at YaR.WebDavMailRu.CloudStore.CloudManager.CreateCloud(HttpListenerBasicIdentity identity)
   at YaR.WebDavMailRu.CloudStore.CloudManager.Instance(IIdentity identityi)
   at YaR.WebDavMailRu.CloudStore.Mailru.StoreBase.MailruStore.GetItemAsync(WebDavUri uri, IHttpContext httpContext)                                                                                          
   at NWebDav.Server.Handlers.PropFindHandler.HandleRequestAsync(IHttpContext httpContext, IStore store)                                                                                                      
   at NWebDav.Server.WebDavDispatcher.DispatchRequestAsync(IHttpContext httpContext)
```

**Comment by yar229** [comment]
Да что-то я и через браузер зайти не могу.
То ли мои аккаунты потёрли, то ли что :)

**Comment by yar229** [comment]
И новый зарегить не могу.
Так что, похоже, это на той стороне что-то сломалось.
Ждём.

**Comment by alexyr** [comment]
Ошибка
Уважаемый пользователь!
По техническим причинам Ваш почтовый ящик временно недоступен.
В ближайшее время работы будут закончены, и доступ в Ваш почтовый ящик будет восстановлен.
Мы приносим свои извинения за доставленные неудобства.

**Comment by barl0g** [comment]
> И новый зарегить не могу.
> Так что, похоже, это на той стороне что-то сломалось.
> Ждём.

Похоже на то.

**Comment by yar229** [comment]
Вроде как починили.

**Comment by yar229** [comment]
https://habr.com/ru/news/t/485626/
