### ISSUE TITLE
Не работает аплоад

### ISSUE THREAD

**Issue by pasha-zzz** [yar229/WebDavMailRuCloud#188]
Аплоад со скоростью чтения с диска, в конце ошибка 500.
1.11.0.20. Скачивается нормально.

**Comment by yar229** [comment]
Не могу подтвердить.
Нужно больше информации.
ОС, дот.нет, коре? На всех файлах/путях или каких-то определённых?

**Comment by pasha-zzz** [comment]
Похоже что только в корень облака, файл любого размера и с любым именем. Те же самые файлы в любую папку грузятся нормально. Папки в корне тоже не создаются.
Вин 10 х64 1909 со всеми обновами. Ну и .нет 4.8 конечно.

**Comment by pasha-zzz** [comment]
Создание папки с именем 123 в корне:

```
[10]: MKCOL:http://127.0.0.1:60801/123/:127.0.0.1:801 - Start processing
[10]: HTTP:POST:https://cloud.mail.ru/api/m1/folder?access_token=xxxxxxxxxxxxx&offset=0&limit=2147483647 (120 ms)
[10]: Unexpected exception while handling request (method=MKCOL, url=http://127.0.0.1:801/123/, source=127.0.0.1:801
System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YaR.Clouds.Base.Requests.BaseRequest`2.<MakeRequestAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YaR.Clouds.Base.Repos.MailRuCloud.WebBin.WebBinRequestRepo.<FolderInfo>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YaR.Clouds.Cloud.<GetItemAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YaR.Clouds.WebDavStore.StoreBase.LocalStore.<GetCollectionAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YaR.Clouds.WebDavStore.CustomHandlers.MkcolHandler.<HandleRequestAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NWebDav.Server.WebDavDispatcher.<DispatchRequestAsync>d__6.MoveNext()
```

**Comment by yar229** [comment]
Ага, принято, спасибо.
На днях починю.

**Comment by yar229** [comment]
Проверяйте, [1.11.0.21](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.11.0.21)

**Comment by yar229** [comment]
Там гитхаб поломался, скачивать не даёт, надеюсь, починят.
