### ISSUE TITLE
Ошибки при заливке файлов на Яндекс.Диск

### ISSUE THREAD

**Issue by yar229** [yar229/WebDavMailRuCloud#193]
http://gallery.ru-board.com/topic.cgi?forum=5&topic=39485&start=1920#21

Altruumann wrote:

> Я и картинку одну залить не могу уже. Файлы на диске появляются, но с нулевым размером и доступа к записи нет.
WebDavMailRuCloud 1.11.0.15
 Через TotalCommander получилось залить. Но неудобно, долго и ошибки то и дело, легче уж через веб-морду. Что ещё остаётся-то? Остались ещё рабочие неофициальные клиенты?

**Comment by yar229** [comment]
Не могу воспроизвести.
Нужна дополнительная информация.
Через недельку-другую закрою таск.

**Comment by Lichtenshtein** [comment]
```
λ wdmrc.exe -p 3332 --protocol YadWeb
  WebDAVCloudMailRu: WebDAV emulator for Cloud.mail.ru
  v.1.11.0.23
  yar229@yandex.ru
[1]: OS Version: Microsoft Windows NT 6.2.9200.0
[1]: CLR: .NET Framework 4.0.30319.42000
[1]: User interactive: True
[1]: Version: 1.11.0.23
[1]: Using proxy:
[1]: Max threads count: 5
[1]: Cloud protocol: YadWeb
[1]: Cache listings, sec: 30
[1]: List query folder depth: 1
[1]: WebDAV server running at http://127.0.0.1:3332/
[5]: OPTIONS:http://127.0.0.1:3332/:127.0.0.1:3332 - Start processing
[5]: OPTIONS:http://127.0.0.1:3332/:127.0.0.1:3332 - Finished processing (36ms, HTTP result: 200)
[5]: PROPFIND:http://127.0.0.1:3332/:127.0.0.1:3332 - Start processing
[5]: Cloud instance created for *****@yandex.ru
[4]: HTTP:GET:https://passport.yandex.ru/auth (538 ms)
[4]: HTTP:POST:https://passport.yandex.ru/registration-validations/auth/multi_step/start (987 ms)
[4]: HTTP:POST:https://passport.yandex.ru/registration-validations/auth/multi_step/commit_password (383 ms)
[4]: HTTP:POST:https://passport.yandex.ru/registration-validations/auth/accounts (388 ms)
[4]: HTTP:GET:https://disk.yandex.ru/client/disk (225 ms)
[5]: HTTP:POST:https://disk.yandex.ru/models/?_m=resources (573 ms)
[5]: HTTP:POST:https://disk.yandex.ru/models/?_m=space (457 ms)
[5]: Loading links from item.links.wdmrc
[5]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (429 ms)
[5]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (388 ms)
[5]: PROPFIND:http://127.0.0.1:3332/:127.0.0.1:3332 - Finished processing (12024ms, HTTP result: 207)
[6]: PROPFIND:http://127.0.0.1:3332/:127.0.0.1:3332 - Start processing
[6]: Cache hit: /
[6]: PROPFIND:http://127.0.0.1:3332/:127.0.0.1:3332 - Finished processing (5ms, HTTP result: 207)
[5]: PROPFIND:http://127.0.0.1:3332/Desktop.ini:127.0.0.1:3332 - Start processing
[5]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (349 ms)
[5]: PROPFIND:http://127.0.0.1:3332/Desktop.ini:127.0.0.1:3332 - Finished processing (353ms, HTTP result: 404)
[6]: PROPFIND:http://127.0.0.1:3332/AutoRun.inf:127.0.0.1:3332 - Start processing
[6]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (286 ms)
[6]: PROPFIND:http://127.0.0.1:3332/AutoRun.inf:127.0.0.1:3332 - Finished processing (287ms, HTTP result: 404)
[5]: PROPFIND:http://127.0.0.1:3332/:127.0.0.1:3332 - Start processing
[5]: Cache hit: /
[6]: PROPFIND:http://127.0.0.1:3332/:127.0.0.1:3332 - Finished processing (48ms, HTTP result: 207)
[10]: PROPFIND:http://127.0.0.1:3332/descript.ion:127.0.0.1:3332 - Start processing
[10]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (276 ms)
[10]: PROPFIND:http://127.0.0.1:3332/descript.ion:127.0.0.1:3332 - Finished processing (278ms, HTTP result: 404)
[8]: PROPFIND:http://127.0.0.1:3332/files.bbs:127.0.0.1:3332 - Start processing
[8]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (342 ms)
[8]: PROPFIND:http://127.0.0.1:3332/files.bbs:127.0.0.1:3332 - Finished processing (343ms, HTTP result: 404)
[6]: PROPFIND:http://127.0.0.1:3332/music/desktop.ini:127.0.0.1:3332 - Start processing
[6]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (263 ms)
[6]: PROPFIND:http://127.0.0.1:3332/music/desktop.ini:127.0.0.1:3332 - Finished processing (264ms, HTTP result: 404)

[5]: PROPFIND:http://127.0.0.1:3332/music:127.0.0.1:3332 - Start processing
[5]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (479 ms)
[11]: PROPFIND:http://127.0.0.1:3332/music:127.0.0.1:3332 - Finished processing (483ms, HTTP result: 207)
[10]: PROPFIND:http://127.0.0.1:3332/music/descript.ion:127.0.0.1:3332 - Start processing
[10]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (405 ms)
[10]: PROPFIND:http://127.0.0.1:3332/music/descript.ion:127.0.0.1:3332 - Finished processing (406ms, HTTP result: 404)
[8]: PROPFIND:http://127.0.0.1:3332/music/files.bbs:127.0.0.1:3332 - Start processing
[8]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (397 ms)
[8]: PROPFIND:http://127.0.0.1:3332/music/files.bbs:127.0.0.1:3332 - Finished processing (398ms, HTTP result: 404)
[10]: PROPFIND:http://127.0.0.1:3332/music/test.exe:127.0.0.1:3332 - Start processing
[10]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (602 ms)
[10]: PROPFIND:http://127.0.0.1:3332/music/test.exe:127.0.0.1:3332 - Finished processing (603ms, HTTP result: 404)
[5]: PUT:http://127.0.0.1:3332/music/test.exe:127.0.0.1:3332 - Start processing
[5]: Cache hit: /music
[5]: Cache hit: /music
[10]: Cache hit: /
[8]: Cache hit: /music
[6]: HTTP:POST:https://disk.yandex.ru/models/?_m=do-resource-upload-url (925 ms)
[5]: PUT:http://127.0.0.1:3332/music/test.exe:127.0.0.1:3332 - Finished processing (2198ms, HTTP result: 201)
[6]: LOCK:http://127.0.0.1:3332/music/test.exe:127.0.0.1:3332 - Start processing
[6]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (680 ms)
[6]: Unexpected exception while handling request (method=LOCK, url=http://127.0.0.1:3332/music/test.exe, source=127.0.0.1:3332
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at NWebDav.Server.Handlers.LockHandler.<HandleRequestAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NWebDav.Server.WebDavDispatcher.<DispatchRequestAsync>d__6.MoveNext()
[10]: PROPFIND:http://127.0.0.1:3332/music/test.exe:127.0.0.1:3332 - Start processing
[10]: Cache hit: /music/test.exe
[10]: PROPFIND:http://127.0.0.1:3332/music/test.exe:127.0.0.1:3332 - Finished processing (1ms, HTTP result: 207)

[6]: PROPFIND:http://127.0.0.1:3332/music/test.exe:127.0.0.1:3332 - Start processing
[6]: Cache hit: /music/test.exe
[6]: PROPFIND:http://127.0.0.1:3332/music/test.exe:127.0.0.1:3332 - Finished processing (0ms, HTTP result: 207) [5]: PROPFIND:http://127.0.0.1:3332/music/test.exe:127.0.0.1:3332 - Start processing
[5]: Cache hit: /music/test.exe
[5]: PROPFIND:http://127.0.0.1:3332/music/test.exe:127.0.0.1:3332 - Finished processing (1ms, HTTP result: 207) [12]: PROPFIND:http://127.0.0.1:3332/music/WinColor.ini:127.0.0.1:3332 - Start processing
[12]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (727 ms)
[12]: PROPFIND:http://127.0.0.1:3332/music/WinColor.ini:127.0.0.1:3332 - Finished processing (729ms, HTTP result: 404)
[5]: PROPFIND:http://127.0.0.1:3332/music/WinColor.ini:127.0.0.1:3332 - Start processing
[5]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (835 ms)
[5]: PROPFIND:http://127.0.0.1:3332/music/WinColor.ini:127.0.0.1:3332 - Finished processing (837ms, HTTP result: 404)
[6]: LOCK:http://127.0.0.1:3332/music/test.exe:127.0.0.1:3332 - Start processing
[6]: Cache hit: /music/test.exe
[6]: Unexpected exception while handling request (method=LOCK, url=http://127.0.0.1:3332/music/test.exe, source=127.0.0.1:3332
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at NWebDav.Server.Handlers.LockHandler.<HandleRequestAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NWebDav.Server.WebDavDispatcher.<DispatchRequestAsync>d__6.MoveNext()
```

**Comment by yar229** [comment]
Ага, спасибо, починю.

Попробуйте явно указать при запуске ключ `--use-locks false`

**Comment by yar229** [comment]
пробуйте [1.11.0.24](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.11.0.24)

**Comment by Lichtenshtein** [comment]
В новой версии загрузка файлов заработала, в предыдущей с ключом тоже, благодарю.

Теперь проблема в том, что файлы не удаляются. Вернее удаляются визуально в проводнике, но на сервере остаются. После нажатия ф5 снова появляются. Или вылезает сообщение что "элемент не найден". Диск примонтирован системными средствами. 

```
[11]: PROPFIND:http://127.0.0.1:3332/music/files.bbs:127.0.0.1:3332 - Start processing
[11]: HTTP:POST:https://disk.yandex.ru/models/?_m=resource,resources (357 ms)
[11]: PROPFIND:http://127.0.0.1:3332/music/files.bbs:127.0.0.1:3332 - Finished processing (359ms, HTTP result: 404)
[8]: DELETE:http://127.0.0.1:3332/music/scripts_2019-12-24_23.01.29.zip:127.0.0.1:3332 - Start processing
[8]: Cache hit: /music
[8]: DELETE:http://127.0.0.1:3332/music/scripts_2019-12-24_23.01.29.zip:127.0.0.1:3332 - Finished processing (0ms, HTTP result: 423)
[11]: DELETE:http://127.0.0.1:3332/music/Sessions%20-%202019-12-24%2023-10-26.json:127.0.0.1:3332 - Start processing
[11]: Cache hit: /music
[11]: DELETE:http://127.0.0.1:3332/music/Sessions%20-%202019-12-24%2023-10-26.json:127.0.0.1:3332 - Finished processing (0ms, HTTP result: 423)
[8]: DELETE:http://127.0.0.1:3332/music/tampermonkey-backup-2019-12-24T23-18-40.127Z.zip:127.0.0.1:3332 - Start processing
[8]: Cache hit: /music
[8]: DELETE:http://127.0.0.1:3332/music/tampermonkey-backup-2019-12-24T23-18-40.127Z.zip:127.0.0.1:3332 - Finished processing (0ms, HTTP result: 423)
[11]: PROPFIND:http://127.0.0.1:3332/music:127.0.0.1:3332 - Start processing
```
