### ISSUE TITLE
YadWeb: The remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by VictorLoktev** [yar229/WebDavMailRuCloud#197]
Ошибка с сегодняшнего дня.
Запуск:
wdmrc.exe --port 12345 --protocol YadWeb 

А дальше вот такое:
`[5]: Cloud instance created for Account
[4]: HTTP:GET:https://passport.yandex.ru/auth (105 ms)
[4]: HTTP:POST:https://passport.yandex.ru/registration-validations/auth/multi_step/start (25 ms)
[5]: Unexpected exception while handling request (method=PROPFIND, url=http://127.0.0.1:12345/, source=127.0.0.1:12345
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
...`

Проверил, к этому же WebDav'у другие клиенты подключаются.
Вчера-позавчера работало.

**Comment by yar229** [comment]
Использование именно протокола YadWeb для вас критично?

**Comment by VictorLoktev** [comment]
Учитывая, что на Яндекс Диск загрузить что-либо можно теперь только двумя способами - руками через браузер или через цепочку программ, включающую данную программу, то с вариантами загрузки без присутствия человека все очень не хорошо. Если речь речь о том, чтобы подождать несколько дней - у меня терпит. Если речь о полном прекращении, то придется искать другой хостинг. А я только перешел от disk.megafon.ru, у них и скорость низкая, и ошибки постоянные, и файлы дублировались (исправили) и содержимое файлов портится (не исправили) ;-)

**Comment by yar229** [comment]
починил, проверяйте [1.11.0.29](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.11.0.29)
