### ISSUE TITLE
System.IO.IOExcept ion: Unable to read data from the transport connection: Удаленный хост принудительно разорвал существующее  подключение

### ISSUE THREAD

**Issue by KoSMM** [yar229/WebDavMailRuCloud#215]
Добрый день, yar229!
Спасибо вам большое за вашу работу и С Новым Годом!

С начала года перестал работать wdmrc. Не могу понять причину. Последний удачный запуск 28 декабря, потом перерыв до 4 января, все последующие запуски с 4 января неудачные.
Обновился до последней версии - не помогло - та же самая ошибка.
Проверил firewall - пропускает все нужные соединения.
Проверил плагином для TotalCommander от pozitronik - работает.

Лог работы в приложении.
`WebDAVCloudMailRu: WebDAV emulator for Cloud.mail.ru
  v.1.11.0.31
  yar229@yandex.ru
[1]: OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
[1]: CLR: .NET Framework 4.0.30319.42000
[1]: User interactive: True
[1]: Version: 1.11.0.31
[1]: Using proxy:
[1]: Max threads count: 5
[1]: Cloud protocol: WebM1Bin
[1]: Cache listings, sec: 30
[1]: List query folder depth: 1
[1]: Use locks: False
[1]: Start as service: False
[1]: WebDAV server running at http://127.0.0.1:3332/
[5]: PROPFIND:http://127.0.0.1:3332/ПУТЬ/:127.0.0.1:3332 - Start processing
[5]: Cloud instance created for ИМЯ@MAIL.ru
[5]: OAuth: authorizing.
[5]: HTTP:POST:https://o2.mail.ru/token (652 ms)
[4]: HTTP:GET:https://cloud.mail.ru/api/m1/user?access_token=TOKEN (410 ms)
[5]: Loading links from item.links.wdmrc
[5]: HTTP:POST:https://cloud.mail.ru/api/m1/folder?access_token= TOKEN &offset=0&limit=2147483647 (139 ms)
[5]: HTTP:POST:https://cloud.mail.ru/api/m1/folder?access_token= TOKEN &offset=0&limit=2147483647 (166 ms)
[5]: PROPFIND:http://127.0.0.1:3332/ПУТЬ/:127.0.0.1:3332 - Finished processin
g (1671ms, HTTP result: 207)
[5]: PUT:http://127.0.0.1:3332/ПУТЬ/duplicati-HASH1.dblock.zip.aes:127.0.0.1:3332 - Start processing
[5]: Cache hit: /ПУТЬ
[5]: Cache hit: /ПУТЬ
[6]: Cache hit: /ПУТЬ
[11]: PUT:http://127.0.0.1:3332/ПУТЬ/duplicati-HASH2.dlist.zip.aes
:127.0.0.1:3332 - Start processing
[11]: Cache hit: /ПУТЬ
[11]: Cache hit: /ПУТЬ
[6]: Cache hit: /ПУТЬ
[10]: HTTP:POST:https://cloud.mail.ru/api/m1/folder?access_token=TOKEN&offset=0&limit=2147483647 (111 ms)
[10]: Requesting new meta server
[6]: HTTP:POST:https://cloud.mail.ru/api/m1/folder?access_token= TOKEN &offset=0&limit=2147483647 (148 ms)
[11]: Requesting new meta server
[4]: HTTP:GET:https://dispatcher.cloud.mail.ru/m (147 ms)
[12]: HTTP:GET:https://dispatcher.cloud.mail.ru/m (125 ms)
[3]: HTTP:GET:https://cloud.mail.ru/api/m1/dispatcher?client_id=cloud-win&access
_token=TOKEN (108 ms)
[4]: HTTP:GET:https://cloud.mail.ru/api/m1/dispatcher?client_id=cloud-win&access
_token=TOKEN (107 ms)
[3]: HTTP:GET:https://dispatcher.cloud.mail.ru/u (2 ms)
[10]: Upload server changed to https://cld-uploader7.cloud.mail.ru/upload/
[12]: HTTP:GET:https://dispatcher.cloud.mail.ru/u (2 ms)
[11]: Upload server changed to https://cld-uploader6.cloud.mail.ru/upload/
[10]: Uploading to /ПУТЬ/duplicati-HASH.dblock.z
ip.aes failed with System.AggregateException: One or more errors occurred. --->
System.Net.Http.HttpRequestException: An error occurred while sending the reques
t. ---> System.Net.WebException: The underlying connection was closed: An unexpe
cted error occurred on a send. ---> System.IO.IOException: Unable to read data f
rom the transport connection: Удаленный хост принудительно разорвал существующее
 подключение. ---> System.Net.Sockets.SocketException: Удаленный хост принудител
ьно разорвал существующее подключение
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, Tr
ansportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar
)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at YaR.Clouds.Base.Repos.MailRuCloud.MailRuBaseRepo.<DoUpload>d__16.MoveNext(
)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at YaR.Clouds.Base.Streams.UploadStreamHttpClient.<Initialize>b__6_0()
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurre
d while sending the request. ---> System.Net.WebException: The underlying connec
tion was closed: An unexpected error occurred on a send. ---> System.IO.IOExcept
ion: Unable to read data from the transport connection: Удаленный хост принудите
льно разорвал существующее подключение. ---> System.Net.Sockets.SocketException:
 Удаленный хост принудительно разорвал существующее подключение
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, Tr
ansportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar
)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at YaR.Clouds.Base.Repos.MailRuCloud.MailRuBaseRepo.<DoUpload>d__16.MoveNext(
)<---
.. далее идут повторные попытки с тем же результатом. 
`

**Comment by yar229** [comment]
И вас с Новым годом!
Ситуация все такая же?
У себя воспроизвести не смог

**Comment by KoSMM** [comment]
Да, ситуация без изменений.
Но, похоже, что проблема моя локальная.

Сегодня потратил много  времени на эксперименты. Экспериментировал с запущенным wdmrc, подключался/тестировал через плагин WebDav для TotalCommander (TC).

1) Прекрасно работает листинг директорий, загрузка файлов из облака.
2) Файлы длиной более 20 байт - не закачиваются с ошибкой выше. При этом в облаке создается файл с соответствующим отправленному файлу именем, но длиной 1 байт, содержащий внутри себя единицу "1" (0x31).
3) Файлы длиной (мистика?!) до 20 байт включительно прекрасно закачиваются.
4) В завершении сделал все тоже самое на другом компе - все работает. Закачка из TC через плагин pozitronik тоже нормально работает. Через web-интерфейс тоже все работает (т.е. проблема не облаке), свободное место в облаке есть. По сему, делаю вывод, что это у меня какой-то локальный баг/глюк на моем отдельно взятом компе.

Если есть идеи, в каком направлении копать, буду признателен. Вообще ума не приложу, как так может получиться, что именно файлы <=20 байт закачиваются, а >20 байт уже нет. Фантастика какая-то.

**Comment by yar229** [comment]
> в облаке создается файл с соответствующим отправленному файлу именем, но длиной 1 байт, содержащий внутри себя единицу "1" (0x31).

Это зависит от клиента, у некоторых есть такая практика - сначала создается файл размеров 1 байт, потом уже закачивается.

> Файлы длиной (мистика?!) до 20 байт включительно прекрасно закачиваются.
Ну про 20 байт понятно, это потому что файлы до 20 байт по другому заливаются.

> Если есть идеи, в каком направлении копать

Вообще, это похоже на то, что файерволл блочит соединение, хотя странно, что при этом листинг/скачивание работает.
Или антивирусу что-то не нравится.

**Comment by KoSMM** [comment]
Путь простой: специально все тесты в корне провожу с именами test1 и т.п.
Я тоже грешу на Firewall, но сегодня (уже вчера) я долго сидел мониторил его соединения - все соединения проходят. Антивирус отключал - это не он, тем более, он у меня трафик по SSL/443 порту не проверяет. Завтра еще Firewall поковыряю. Возможно, он разрешает соединения, но по какой-то неведомой причине потом их рвет. Но это тоже странно, т.к. а) все остальное работает б) я ничего не менял довольно давно (я вообще в настройки FW редко залезаю).

**Comment by ralexxx** [comment]
Здравствуйте! Всех с праздниками!
Установлен WebDAVCloudMailRu-1.13.1.1-dotNet48
До Нового года заходил и все работало.
Обратил внимание, что с 10-12 января 2021 не смог ничего записать на диск под управлением WebDavMailRuCloud.
Диск открывается, директории открываются. Но…
Файлы не открываются и не записываются. Просмотр также невозможен. 
Спасибо!

**Comment by KoSMM** [comment]
А какая у версия ОС?
Сейчас на 4pda (последняя страница в теме про CloudMailRu) прочитал, что у кого-то похожая проблема в TC. Тоже не могут после нового года зайти в облако.
У меня проблема, как я описал выше: я не могу только записать в облако. При чем я перерыл все настройки FW, отсмотрел все заблокированные пакеты - облако не блокируется. Но записать я так и не смог. Авторизация, загрузка ко мне, листинг файлов - все работает. Не работет только закачка в облако. У меня Windows 7. Под Win10 все работает.

**Comment by ralexxx** [comment]
> А какая у версия ОС?

У меня Win 7-64 bit , на 8.1 и 10 работает, я проверил. 
Будем ждать обновления, либо уповать на то, что уважаемый разработчик yar229 живет под семеркой. 
Проблема появилась после 14 января 16:27 (время последней записи на диск)

**Comment by yar229** [comment]
Интересно как...
На днях попробую на семерке под ВМ

**Comment by yar229** [comment]
Проверяйте [1.13.1.2](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.13.1.2)

**Comment by KoSMM** [comment]
Работает, спасибо!

**Comment by ralexxx** [comment]
> Проверяйте [1.13.1.2](https://github.com/yar229/WebDavMailRuCloud/releases/tag/1.13.1.2)

Спасибо огромное! Все работает! Вернули к жизни! Дай вам бог всего!!!
