### ISSUE TITLE
One or more errors occurred. (Cannot get X-Default-UID)

### ISSUE THREAD

**Issue by Kr00t** [yar229/WebDavMailRuCloud#228]
Что я упускаю? 
user@webdav:~/yandex$ sudo dotnet wdmrc.dll --use-deduplicate --protocol YadWeb -h http://* --use-locks
  WebDAVCloudMailRu: WebDAV emulator for Cloud.mail.ru
  v.1.13.5.2
  yar229@yandex.ru
[1]: OS Version: Unix 5.4.0.110
[1]: CLR: .NET 5.0.17
[1]: User interactive: True
[1]: Version: 1.13.5.2
[1]: Using proxy:
[1]: Max threads count: 5
[1]: Cloud protocol: YadWeb
[1]: Cache listings, sec: 30
[1]: List query folder depth: 1
[1]: Use locks: True
[1]: Use deduplicate: True
[1]: Start as service: False
[1]: WebDAV server running at http://*:801/
[4]: PROPFIND:http://172.16.254.103:801/:172.16.254.103:801 - Start processing
[4]: Cloud instance created for XXXXXX@yandex.ru
[7]: HTTP:GET:https://passport.yandex.ru/auth (653 ms)
[7]: HTTP:POST:https://passport.yandex.ru/registration-validations/auth/multi_step/start (558 ms)
[6]: HTTP:POST:https://passport.yandex.ru/registration-validations/auth/multi_step/commit_password (597 ms)
[4]: Unexpected exception while handling request (method=PROPFIND, url=http://172.16.254.103:801/, source=172.16.254.103:801
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Cannot get X-Default-UID))
 ---> System.AggregateException: One or more errors occurred. (Cannot get X-Default-UID)
 ---> System.Security.Authentication.AuthenticationException: Cannot get X-Default-UID
   at YaR.Clouds.Base.Repos.YandexDisk.YadWeb.Requests.YadAuthPasswordRequest.DeserializeMessage(NameValueCollection responseHeaders, Stream stream) in D:\a\1\s\MailRuCloud\MailRuCloudApi\Base\Repos\YandexDisk\YadWeb\Requests\YadAuthPasswordRequest.cs:line 74
   at YaR.Clouds.Base.Requests.BaseRequest`2.MakeRequestAsync() in D:\a\1\s\MailRuCloud\MailRuCloudApi\Base\Requests\BaseRequest.cs:line 95
   at YaR.Clouds.Base.Requests.BaseRequest`2.MakeRequestAsync() in D:\a\1\s\MailRuCloud\MailRuCloudApi\Base\Requests\BaseRequest.cs:line 95
   at YaR.Clouds.Base.Repos.YandexDisk.YadWeb.YadWebAuth.MakeLogin() in D:\a\1\s\MailRuCloud\MailRuCloudApi\Base\Repos\YandexDisk\YadWeb\YadWebAuth.cs:line 41
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at YaR.Clouds.Base.Repos.YandexDisk.YadWeb.YadWebAuth..ctor(HttpCommonSettings settings, IBasicCredentials creds) in D:\a\1\s\MailRuCloud\MailRuCloudApi\Base\Repos\YandexDisk\YadWeb\YadWebAuth.cs:line 19
   at YaR.Clouds.Base.Repos.YandexDisk.YadWeb.YadWebRequestRepo.<get_CachedAuth>b__10_0(YadWebAuth _) in D:\a\1\s\MailRuCloud\MailRuCloudApi\Base\Repos\YandexDisk\YadWeb\YadWebRequestRepo.cs:line 56
   at YaR.Clouds.Common.Cached`1.<>c__DisplayClass8_0.<RefreshValueIfNeeded>b__0() in D:\a\1\s\MailRuCloud\MailRuCloudApi\Common\Cached.cs:line 40
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at YaR.Clouds.Common.Cached`1.RefreshValueIfNeeded() in D:\a\1\s\MailRuCloud\MailRuCloudApi\Common\Cached.cs:line 42
   at YaR.Clouds.Common.Cached`1..ctor(Func`2 valueFactory, Func`2 duration) in D:\a\1\s\MailRuCloud\MailRuCloudApi\Common\Cached.cs:line 26
   at YaR.Clouds.Base.Repos.YandexDisk.YadWeb.YadWebRequestRepo.get_CachedAuth() in D:\a\1\s\MailRuCloud\MailRuCloudApi\Base\Repos\YandexDisk\YadWeb\YadWebRequestRepo.cs:line 56
   at YaR.Clouds.Base.Repos.YandexDisk.YadWeb.YadWebRequestRepo.get_Authent() in D:\a\1\s\MailRuCloud\MailRuCloudApi\Base\Repos\YandexDisk\YadWeb\YadWebRequestRepo.cs:line 54
   at YaR.Clouds.Base.Repos.YandexDisk.YadWeb.YadWebRequestRepo.AccountInfo() in D:\a\1\s\MailRuCloud\MailRuCloudApi\Base\Repos\YandexDisk\YadWeb\YadWebRequestRepo.cs:line 284
   at YaR.Clouds.Base.Account.LoginAsync() in D:\a\1\s\MailRuCloud\MailRuCloudApi\Base\Account.cs:line 54
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at YaR.Clouds.Base.Account.Login() in D:\a\1\s\MailRuCloud\MailRuCloudApi\Base\Account.cs:line 44
   at YaR.Clouds.Cloud..ctor(CloudSettings settings, Credentials credentials) in D:\a\1\s\MailRuCloud\MailRuCloudApi\Cloud.cs:line 60
   at YaR.Clouds.WebDavStore.CloudManager.CreateCloud(HttpListenerBasicIdentity identity) in D:\a\1\s\WebDavMailRuCloudStore\CloudManager.cs:line 46
   at YaR.Clouds.WebDavStore.CloudManager.Instance(IIdentity identityi) in D:\a\1\s\WebDavMailRuCloudStore\CloudManager.cs:line 28
   at YaR.Clouds.WebDavStore.StoreBase.LocalStore.GetItemAsync(WebDavUri uri, IHttpContext httpContext) in D:\a\1\s\WebDavMailRuCloudStore\StoreBase\LocalStore.cs:line 37
   at NWebDav.Server.Handlers.PropFindHandler.HandleRequestAsync(IHttpContext httpContext, IStore store) in D:\a\1\s\NWebDav\NWebDav.Server\Handlers\PropFindHandler.cs:line 77
   at NWebDav.Server.WebDavDispatcher.DispatchRequestAsync(IHttpContext httpContext) in D:\a\1\s\NWebDav\NWebDav.Server\WebDavDispatcher.cs:line 137

**Comment by yar229** [comment]
В вашем случае Яндекс требует дополнительного подтверждения (капчу или смс или чего еще).
Надо с этого IP/подсети зайти пару-тройку раз в браузере, подтвердить, и тогда будет пускать.

**Comment by Kr00t** [comment]
Первую проблему решил, приложение на docker запустил. А как быть с этой ? 
"One or more errors occurred. (YadAuthPasswordRequest errors: captcha.required))"

**Comment by MGSDS** [comment]
У меня такая же проблема, при входе с браузера не просит ни капчу, ни код, но приложение не работает. Также пробовал указать user-agent моего браузера, тоже не помогает.

**Comment by ZimM-LostPolygon** [comment]
Та же проблема. С браузера заходит, не требуя никаких подтверждений. Залогинивался-разлогинивался в браузере несколько раз - всё ок, но через приложение получаю `Cannot get X-Default-UID`

**Comment by alexgoussev** [comment]
Та же фигня

**Comment by wadim-al** [comment]
Если настроен тип входа в почту "пароль", 2FA выключен, то работает только через пароль от почты.
Если настроен тип входа в почту "пароль", 2FA выключен, создан и введен пароль приложения для диска, то происходит эта ошибка.
Если настроен хотя бы sms, то ошибка происходит и при использовании пароля от почты, и при использовании пароля приложения для диска.

**Comment by leonsoft-kras** [comment]
> Если настроен тип входа в почту "пароль", 2FA выключен, то работает только через пароль от почты. Если настроен тип входа в почту "пароль", 2FA выключен, создан и введен пароль приложения для диска, то происходит эта ошибка. Если настроен хотя бы sms, то ошибка происходит и при использовании пароля от почты, и при использовании пароля приложения для диска.

Простой пароль. 2FA отсутствует. Пароли приложений - выключены. Ошибка - происходит.

**Comment by VictorLoktev** [comment]
Сегодня при входе в Яндекс Диск снова показывается страница с рекламой "диких" скидок.
И снова, как и раньше при показе рекламы со скидками не работает вход приложения.
Есть подозрение, что во время "сезона" скидок меняется параметризация входа, возможно ожидается какой-то параметр в URL'е или еще что.
Уже не первый раз замечено - как скидки, так сбоит утренний бэкап.

**Comment by yar229** [comment]
Спасибо, постараюсь глянуть на днях

**Comment by hondaspb** [comment]
> Спасибо, постараюсь глянуть на днях

@yar229 Скажите пожалуйста, удалось глянуть?
