### ISSUE TITLE
Error during synchronization in linux (rsync)

### ISSUE THREAD

**Issue by ksergk** [yar229/WebDavMailRuCloud#229]
WebDAVCloudMailRu-1.13.5.2-dotNet5-1
или
WebDAVCloudMailRu-1.13.5.2-dotNetCore31
LinuxMint 
5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Запускаю приложение
' dotnet ~/Programm/MailRu-WebDav/Exec/wdmrc.dll -p 8888 --cache-listing-depth 2  -h http://127.0.0.3'

Запускаю синхронизацию через rsync локального каталога в 
'/run/user/1000/gvfs/dav:host=127.0.0.3,port=8888,ssl=false'
Через какое-то время приложение падает. В логе сообщение:

```[4]: Global exception
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
   at System.Net.HttpListenerResponse.CheckDisposed()
   at System.Net.HttpListenerResponse.set_EntitySendFormat(EntitySendFormat value)
   at NWebDav.Server.HttpListener.HttpBaseContext..ctor(HttpListenerRequest request, HttpListenerResponse response) in D:\a\1\s\NWebDav\NWebDav.Server.HttpListener\HttpBaseContext.cs:line 20
   at NWebDav.Server.HttpListener.HttpBasicContext..ctor(HttpListenerContext httpListenerContext, Func`2 checkIdentity) in D:\a\1\s\NWebDav\NWebDav.Server.HttpListener\BasicHttpContext.cs:line 29
   at YaR.Clouds.Console.Payload.DispatchHttpRequestsAsync(HttpListener httpListener, Int32 maxThreadCount)```

**Comment by ksergk** [comment]
Решилось установкой параметра 
 --maxthreads 100

**Comment by yar229** [comment]
1. Рекомендуется перейти на .нет5
2. Прецедентов вроде бы не было, но с кол-вом потоков на всякий случай будьте аккуратнее, мало ли, мейлру усмотрит "нежелательную активность"
