### ISSUE TITLE
Unhandled exception. System.Net.HttpListenerException (5): Отказано в доступе.

### ISSUE THREAD

**Issue by ramil-h** [yar229/WebDavMailRuCloud#239]
Подскажите, что я не так делаю?

c:\WDMRC>wdmrc.exe --port 801 --install
  WebDAVCloudMailRu: WebDAV emulator for Cloud.mail.ru
  v.1.13.6.1
  yar229@yandex.ru
[1]: OS Version: Microsoft Windows NT 10.0.22621.0
[1]: CLR: .NET 6.0.14
[1]: User interactive: True
[1]: Version: 1.13.6.1
[1]: Using proxy:
[1]: Max threads count: 5
[1]: Cloud protocol: WebM1Bin
[1]: Cache listings, sec: 30
[1]: List query folder depth: 1
[1]: Use locks: False
[1]: Use deduplicate: False
[1]: Start as service: False
Unhandled exception. System.Net.HttpListenerException (5): Отказано в доступе.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at YaR.Clouds.Console.Payload.Run(CommandLineOptions options)
   at YaR.Clouds.Console.Program.<>c.<Main>b__1_0(CommandLineOptions options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at YaR.Clouds.Console.Program.Main(String[] args)

**Comment by ramil-h** [comment]
Вопрос снимается.
